# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup PowerShell module cache
        uses: actions/cache@v2
        id: cacher
        with:
          path: "~/.local/share/powershell/Modules"
          key: crescendo-cache
        - name: Install Crescendo
          if: steps.cacher.outputs.cache-hit != 'true'
          shell: pwsh
          run: Install-Module Microsoft.PowerShell.Crescendo -RequiredVersion 0.4.1 -Force
      - name: Build the module with Crescendo
        run: .\build.ps1
      - name: Bundle up module
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: module
          path: ./src/
  Test:
    needs: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download module
        uses: actions/download-artifact@v2
        with:
          name: module
          path: C:\Users\runneradmin\Documents\PowerShell\Modules\Foil\
      - name: Test with Pester
        run: Invoke-Pester -CI -Output Detailed
      - name: Upload Pester test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: testResults.xml
      - name: Upload Chocolatey logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: choco-logs
          path: C:\ProgramData\chocolatey\logs\
  Results:
    needs: Test
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: test-results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/**/*.xml